version = 0.1
[default.deploy.parameters]
stack_name = "lululemon-productdetails"
resolve_s3 = true
s3_prefix = "lululemon-productdetails"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
